### YamlMime:ManagedReference
items:
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  commentId: T:AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  id: ASMSettings.SettingsProxy
  parent: AdvancedSceneManager.Models
  children:
  - AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
  - AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
  - AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
  langs:
  - csharp
  - vb
  name: ASMSettings.SettingsProxy
  nameWithType: ASMSettings.SettingsProxy
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  type: Class
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: SettingsProxy
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 21
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  summary: Used to make <xref href="AdvancedSceneManager.SceneManager.settings" data-throw-if-not-resolved="false"></xref> a bit more intuitive.
  example: []
  syntax:
    content: public class SettingsProxy
    content.vb: Public Class SettingsProxy
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
  commentId: P:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
  id: local
  parent: AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  langs:
  - csharp
  - vb
  name: local
  nameWithType: ASMSettings.SettingsProxy.local
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
  type: Property
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: local
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 25
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  summary: The local asm settings, not synced to source.
  example: []
  syntax:
    content: public ASMSettings.Local local { get; }
    parameters: []
    return:
      type: AdvancedSceneManager.Models.ASMSettings.Local
    content.vb: Public ReadOnly Property local As ASMSettings.Local
  overload: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
  commentId: P:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
  id: project
  parent: AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  langs:
  - csharp
  - vb
  name: project
  nameWithType: ASMSettings.SettingsProxy.project
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
  type: Property
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: project
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 28
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  summary: The project-wide asm settings.
  example: []
  syntax:
    content: public ASMSettings project { get; }
    parameters: []
    return:
      type: AdvancedSceneManager.Models.ASMSettings
    content.vb: Public ReadOnly Property project As ASMSettings
  overload: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
  commentId: P:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
  id: profile
  parent: AdvancedSceneManager.Models.ASMSettings.SettingsProxy
  langs:
  - csharp
  - vb
  name: profile
  nameWithType: ASMSettings.SettingsProxy.profile
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
  type: Property
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: profile
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 31
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  summary: The profile-wide asm settings.
  example: []
  syntax:
    content: public Profile profile { get; }
    parameters: []
    return:
      type: AdvancedSceneManager.Models.Profile
    content.vb: Public ReadOnly Property profile As Profile
  overload: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: AdvancedSceneManager.SceneManager.settings
  commentId: P:AdvancedSceneManager.SceneManager.settings
  isExternal: true
- uid: AdvancedSceneManager.Models
  commentId: N:AdvancedSceneManager.Models
  name: AdvancedSceneManager.Models
  nameWithType: AdvancedSceneManager.Models
  fullName: AdvancedSceneManager.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local*
  commentId: Overload:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
  name: local
  nameWithType: ASMSettings.SettingsProxy.local
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.local
- uid: AdvancedSceneManager.Models.ASMSettings.Local
  commentId: T:AdvancedSceneManager.Models.ASMSettings.Local
  parent: AdvancedSceneManager.Models
  name: ASMSettings.Local
  nameWithType: ASMSettings.Local
  fullName: AdvancedSceneManager.Models.ASMSettings.Local
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project*
  commentId: Overload:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
  name: project
  nameWithType: ASMSettings.SettingsProxy.project
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.project
- uid: AdvancedSceneManager.Models.ASMSettings
  commentId: T:AdvancedSceneManager.Models.ASMSettings
  parent: AdvancedSceneManager.Models
  name: ASMSettings
  nameWithType: ASMSettings
  fullName: AdvancedSceneManager.Models.ASMSettings
- uid: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile*
  commentId: Overload:AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
  name: profile
  nameWithType: ASMSettings.SettingsProxy.profile
  fullName: AdvancedSceneManager.Models.ASMSettings.SettingsProxy.profile
- uid: AdvancedSceneManager.Models.Profile
  commentId: T:AdvancedSceneManager.Models.Profile
  parent: AdvancedSceneManager.Models
  name: Profile
  nameWithType: Profile
  fullName: AdvancedSceneManager.Models.Profile
