### YamlMime:ManagedReference
items:
- uid: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  commentId: T:AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  id: ASMSettings.Local.SaveAction
  parent: AdvancedSceneManager.Models
  children:
  - AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.DoNothing
  - AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Prompt
  - AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Save
  langs:
  - csharp
  - vb
  name: ASMSettings.Local.SaveAction
  nameWithType: ASMSettings.Local.SaveAction
  fullName: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  type: Enum
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: SaveAction
    path: ../../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 124
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  syntax:
    content: public enum SaveAction
    content.vb: Public Enum SaveAction
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.DoNothing
  commentId: F:AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.DoNothing
  id: DoNothing
  parent: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  langs:
  - csharp
  - vb
  name: DoNothing
  nameWithType: ASMSettings.Local.SaveAction.DoNothing
  fullName: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.DoNothing
  type: Field
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: DoNothing
    path: ../../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 126
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  syntax:
    content: DoNothing = 0
    return:
      type: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Save
  commentId: F:AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Save
  id: Save
  parent: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  langs:
  - csharp
  - vb
  name: Save
  nameWithType: ASMSettings.Local.SaveAction.Save
  fullName: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Save
  type: Field
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: Save
    path: ../../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 126
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  syntax:
    content: Save = 1
    return:
      type: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Prompt
  commentId: F:AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Prompt
  id: Prompt
  parent: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  langs:
  - csharp
  - vb
  name: Prompt
  nameWithType: ASMSettings.Local.SaveAction.Prompt
  fullName: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction.Prompt
  type: Field
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: Prompt
    path: ../../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Models/ASMSettings.cs
    startLine: 126
  assemblies:
  - AdvancedSceneManager
  namespace: AdvancedSceneManager.Models
  syntax:
    content: Prompt = 2
    return:
      type: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: AdvancedSceneManager.Models
  commentId: N:AdvancedSceneManager.Models
  name: AdvancedSceneManager.Models
  nameWithType: AdvancedSceneManager.Models
  fullName: AdvancedSceneManager.Models
- uid: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  commentId: T:AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
  parent: AdvancedSceneManager.Models
  name: ASMSettings.Local.SaveAction
  nameWithType: ASMSettings.Local.SaveAction
  fullName: AdvancedSceneManager.Models.ASMSettings.Local.SaveAction
