### YamlMime:ManagedReference
items:
- uid: AdvancedSceneManager.Editor.SettingsTab
  commentId: T:AdvancedSceneManager.Editor.SettingsTab
  id: SettingsTab
  parent: AdvancedSceneManager.Editor
  children:
  - AdvancedSceneManager.Editor.SettingsTab.InitializeProfile(UnityEngine.UIElements.VisualElement,System.Action)
  - AdvancedSceneManager.Editor.SettingsTab.OnEnable(UnityEngine.UIElements.VisualElement)
  - AdvancedSceneManager.Editor.SettingsTab.Settings
  langs:
  - csharp
  - vb
  name: SettingsTab
  nameWithType: SettingsTab
  fullName: AdvancedSceneManager.Editor.SettingsTab
  type: Class
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: SettingsTab
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
    startLine: 17
  assemblies:
  - AdvancedSceneManager.Editor
  namespace: AdvancedSceneManager.Editor
  syntax:
    content: public static class SettingsTab
    content.vb: Public Module SettingsTab
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: AdvancedSceneManager.Editor.SettingsTab.Settings
  commentId: P:AdvancedSceneManager.Editor.SettingsTab.Settings
  id: Settings
  parent: AdvancedSceneManager.Editor.SettingsTab
  langs:
  - csharp
  - vb
  name: Settings
  nameWithType: SettingsTab.Settings
  fullName: AdvancedSceneManager.Editor.SettingsTab.Settings
  type: Property
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: Settings
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
    startLine: 20
  assemblies:
  - AdvancedSceneManager.Editor
  namespace: AdvancedSceneManager.Editor
  syntax:
    content: public static SettingsTab Settings { get; }
    parameters: []
    return:
      type: AdvancedSceneManager.Editor.Utility.SettingsTab
    content.vb: Public Shared ReadOnly Property Settings As SettingsTab
  overload: AdvancedSceneManager.Editor.SettingsTab.Settings*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: AdvancedSceneManager.Editor.SettingsTab.OnEnable(UnityEngine.UIElements.VisualElement)
  commentId: M:AdvancedSceneManager.Editor.SettingsTab.OnEnable(UnityEngine.UIElements.VisualElement)
  id: OnEnable(UnityEngine.UIElements.VisualElement)
  parent: AdvancedSceneManager.Editor.SettingsTab
  langs:
  - csharp
  - vb
  name: OnEnable(VisualElement)
  nameWithType: SettingsTab.OnEnable(VisualElement)
  fullName: AdvancedSceneManager.Editor.SettingsTab.OnEnable(UnityEngine.UIElements.VisualElement)
  type: Method
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: OnEnable
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
    startLine: 163
  assemblies:
  - AdvancedSceneManager.Editor
  namespace: AdvancedSceneManager.Editor
  syntax:
    content: public static void OnEnable(VisualElement element)
    parameters:
    - id: element
      type: UnityEngine.UIElements.VisualElement
    content.vb: Public Shared Sub OnEnable(element As VisualElement)
  overload: AdvancedSceneManager.Editor.SettingsTab.OnEnable*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: AdvancedSceneManager.Editor.SettingsTab.InitializeProfile(UnityEngine.UIElements.VisualElement,System.Action)
  commentId: M:AdvancedSceneManager.Editor.SettingsTab.InitializeProfile(UnityEngine.UIElements.VisualElement,System.Action)
  id: InitializeProfile(UnityEngine.UIElements.VisualElement,System.Action)
  parent: AdvancedSceneManager.Editor.SettingsTab
  langs:
  - csharp
  - vb
  name: InitializeProfile(VisualElement, Action)
  nameWithType: SettingsTab.InitializeProfile(VisualElement, Action)
  fullName: AdvancedSceneManager.Editor.SettingsTab.InitializeProfile(UnityEngine.UIElements.VisualElement, System.Action)
  type: Method
  source:
    remote:
      path: Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
      branch: dev
      repo: https://github.com/Lazy-Solutions/Unity.AdvancedSceneManager.git
    id: InitializeProfile
    path: ../../Unity.AdvancedSceneManager/Unity projects/ASM-dev-2019/Assets/AdvancedSceneManager/System/Editor/Windows/Tabs/SettingsTab.cs
    startLine: 341
  assemblies:
  - AdvancedSceneManager.Editor
  namespace: AdvancedSceneManager.Editor
  syntax:
    content: public static void InitializeProfile(VisualElement element, Action changedCallback)
    parameters:
    - id: element
      type: UnityEngine.UIElements.VisualElement
    - id: changedCallback
      type: System.Action
    content.vb: Public Shared Sub InitializeProfile(element As VisualElement, changedCallback As Action)
  overload: AdvancedSceneManager.Editor.SettingsTab.InitializeProfile*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: AdvancedSceneManager.Editor
  commentId: N:AdvancedSceneManager.Editor
  name: AdvancedSceneManager.Editor
  nameWithType: AdvancedSceneManager.Editor
  fullName: AdvancedSceneManager.Editor
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: AdvancedSceneManager.Editor.SettingsTab.Settings*
  commentId: Overload:AdvancedSceneManager.Editor.SettingsTab.Settings
  name: Settings
  nameWithType: SettingsTab.Settings
  fullName: AdvancedSceneManager.Editor.SettingsTab.Settings
- uid: AdvancedSceneManager.Editor.Utility.SettingsTab
  commentId: T:AdvancedSceneManager.Editor.Utility.SettingsTab
  parent: AdvancedSceneManager.Editor.Utility
  name: SettingsTab
  nameWithType: SettingsTab
  fullName: AdvancedSceneManager.Editor.Utility.SettingsTab
- uid: AdvancedSceneManager.Editor.Utility
  commentId: N:AdvancedSceneManager.Editor.Utility
  name: AdvancedSceneManager.Editor.Utility
  nameWithType: AdvancedSceneManager.Editor.Utility
  fullName: AdvancedSceneManager.Editor.Utility
- uid: AdvancedSceneManager.Editor.SettingsTab.OnEnable*
  commentId: Overload:AdvancedSceneManager.Editor.SettingsTab.OnEnable
  name: OnEnable
  nameWithType: SettingsTab.OnEnable
  fullName: AdvancedSceneManager.Editor.SettingsTab.OnEnable
- uid: UnityEngine.UIElements.VisualElement
  commentId: T:UnityEngine.UIElements.VisualElement
  parent: UnityEngine.UIElements
  isExternal: true
  name: VisualElement
  nameWithType: VisualElement
  fullName: UnityEngine.UIElements.VisualElement
- uid: UnityEngine.UIElements
  commentId: N:UnityEngine.UIElements
  isExternal: true
  name: UnityEngine.UIElements
  nameWithType: UnityEngine.UIElements
  fullName: UnityEngine.UIElements
- uid: AdvancedSceneManager.Editor.SettingsTab.InitializeProfile*
  commentId: Overload:AdvancedSceneManager.Editor.SettingsTab.InitializeProfile
  name: InitializeProfile
  nameWithType: SettingsTab.InitializeProfile
  fullName: AdvancedSceneManager.Editor.SettingsTab.InitializeProfile
- uid: System.Action
  commentId: T:System.Action
  parent: System
  isExternal: true
  name: Action
  nameWithType: Action
  fullName: System.Action
