name: Combine Docs into Single File for GPT

on:
  push:
    paths:
      - 'docs/**.md'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Combine markdown files into ai.txt
        run: |
          REPO="Lazy-Solutions/AdvancedSceneManager"
          BRANCH="main"
          DOCS_PATH="docs"
          OUTPUT_FILE="ai.txt"
          
          : > "$OUTPUT_FILE"

          find "$DOCS_PATH" -name "*.md" \
            ! -path "$DOCS_PATH/api/*" \
            | sort | while read md_file; do
              clean_path="${md_file#./}"
              url="https://github.com/${REPO}/blob/${BRANCH}/${clean_path}"
              echo "Adding $url to output"
              echo "<!-- ${url} -->" >> "$OUTPUT_FILE"
              echo >> "$OUTPUT_FILE"
              cat "$md_file" >> "$OUTPUT_FILE"
              echo -e "\n\n" >> "$OUTPUT_FILE"
          done

      - name: Upload ai.txt as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpt-docs
          path: ai.txt
