
name: Create release

on:
  push:
    branches:
    - main
    paths:
    - 'patches/**.unitypackage'

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changed-files.outputs.all_changed_files }}[0];
          release_name: ${{ steps.changed-files.outputs.all_changed_files }}[0]
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
